version: "3.8"
services:
  dynamoDB:
    image: amazon/dynamodb-local:1.13.5
    ports:
      - 8000:8000
  api:
    build:
      context: .
      target: prod
    depends_on: 
      - dynamoDB
    ports:
      - 8080:8080
    environment:
      - DEFAULT_SCAN_LIMIT=5
      - SEED_LIMIT=20
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=some-key
      - AWS_SECRET_ACCESS_KEY=some-key
      - PORT=8080
      - DYNAMO_DB_ENDPOINT=http://dynamoDB:8000